Add syndication boxnumber table
Informatievlaanderen/address-registry pull request #755
Opened 2022-09-19 13:05 UTC by emalfroy

2022-09-19 14:31 UTC, jvandaal approved these changes

2022-09-20 06:17 UTC, lvermeulen commented on src/AddressRegistry.Projections.Legacy/Migrations/20220919142202_AddAddressBoxNumberSyndicationHelper.cs
> +﻿using System;
move inside namespace

2022-09-20 06:24 UTC, ArneD requested changes

2022-09-20 06:24 UTC, ArneD commented on src/AddressRegistry.Projections.Legacy/AddressSyndication/AddressSyndicationExtensions.cs
> +    using Microsoft.VisualBasic;
uhm?

2022-09-20 06:52 UTC, emalfroy commented on src/AddressRegistry.Projections.Legacy/Migrations/20220919142202_AddAddressBoxNumberSyndicationHelper.cs
> +﻿using System;
Done

2022-09-20 06:52 UTC, emalfroy commented on src/AddressRegistry.Projections.Legacy/AddressSyndication/AddressSyndicationExtensions.cs
> +    using Microsoft.VisualBasic;
removed

2022-09-20 06:53 UTC, merged